### ISSUE TITLE
invalid Indentation

### ISSUE THREAD

**Issue by zmsp** [ShipengWang/HyperAdam-Tensorflow#6]
https://github.com/ShipengWang/HyperAdam-Tensorflow/blob/3cb9a017bd9f74e370232dc15b67e276900fcc67/adamLSTM/nn_opt/__init__.py#L325

```
ssubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import task_list
  File "/HyperAdam-Tensorflow/adamLSTM/task_list.py", line 3, in <module>
    import nn_opt
  File "/HyperAdam-Tensorflow/adamLSTM/nn_opt/__init__.py", line 325
    for i in range(n_steps / s):
                               ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by ShipengWang** [comment]
Thanks! This error has been removed.
